version: '3'
services:
  vue-ssr:
    build: .
    container_name: vue-ssr
    env_file:
      - .env
    tty: true
    stdin_open: true
    environment:
      HOST: 0.0.0.0
    volumes:
      - ./:/app
    ports:
      - ${DEV_PORT}:${APP_PORT}
    command:
      - /bin/sh
      - '-c'
      - 'npm rebuild node-sass && npm run dev'
